import * as defs from "./definitions";

export * from "./definitions/";
export * from "./spec";

export const MAINNET_CHAINS = [
	defs.arbitrum,
	defs.base,
	defs.boba,
	defs.bsc,
	defs.filecoin,
	defs.mainnet,
	defs.optimism,
	defs.polygon,
	defs.rootstock,
	defs.scroll,
	defs.zkSync,
	defs.linea,
	defs.taiko,
	defs.mantle,
	defs.sei,
	defs.bob,
	defs.gnosis,
	defs.metal,
	defs.corn,
	defs.sonic,
	defs.celo,
	defs.hemi,
	defs.telos,
	defs.saga,
	defs.goat,
	defs.redbelly,
	defs.lightlink,
	defs.worldchain,
	defs.xdc,
	defs.tronShasta,
	defs.lens,
	defs.nibiru,
	defs.etherlink,
	defs.unichain,
	defs.matchain,
] as const;
