import * as defs from "./definitions";
export * from "./definitions/";
export * from "./spec";

export const MAINNET_CHAINS = [
  defs.arbitrum,
  defs.base,
  defs.boba,
  defs.blast,
  defs.bsc,
  defs.filecoin,
  defs.mainnet,
  defs.moonbeam,
  defs.optimism,
  defs.polygon,
  defs.rootstock,
  defs.scroll,
  defs.polygonZkEvm,
  defs.zkSync,
  defs.manta,
  defs.linea,
  defs.taiko,
  defs.mantle,
  defs.sei,
  defs.lisk,
  defs.bob,
  defs.gnosis,
  defs.xLayer,
  defs.metal,
  defs.corn,
  defs.sonic,
  defs.celo,
  defs.hemi,
  defs.telos,
  defs.saga,
] as const;
